framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    validation: { enable_annotations: true }
    #form: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            upload:
                base_path: "uploads"
            admin:
                base_path: "build/admin"

    cache:
        prefix_seed: "%env(CACHE_PREFIX)%"
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

when@test:
    framework:
        test: true
        session:
            storage_id: session.storage.mock_file
